export default {
  DEFAULT_PADDING: 40,
  DEFAULT_PADDING_MULTIPLE_TIMES: 2,
  DEFAULT_PADDING_DIVISION_TIMES: 2,
  DEFAULT_DIGIT: 10,
  AXIS_LABEL_LINE_SIZE: 5,
  Y_AXIS_UNIT: 6,
  X_AXIS_LABEL_PADDING_MULTIPLE_TIMES: 1.5,
  Y_AXIS_LABEL_PADDING_MULTIPLE_TIMES: 1.6,
}
